name: CI/CD
run-name: Build Docker Images
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
      VITE_SUPABASE_ANON_KEY: ${{secrets.VITE_SUPABASE_ANON_KEY}}
    steps:
      - name: checkout codebase
        uses: actions/checkout@v5
      - name: build docker images
        run: docker build . -t git.workshop.bteklabs.com/zaltsani/greeter-bebas-aja-yah:latest
      - name: login to docker
        run: echo ${{secrets.WORKSHOP_TOKEN}} | docker login --username zaltsani --password-stdin git.workshop.bteklabs.com
      - name: push images to registry
        run: docker push git.workshop.bteklabs.com/zaltsani/greeter-bebas-aja-yah:latest